apiVersion: apps/v1

kind: Deployment

metadata:
  name: california-housing-api
  namespace: california-housing

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: california-housing-api

  template:
    metadata:
      labels:
        app: california-housing-api

    spec:
      containers:
        - name: california-housing-api

          image: ghcr.io/pkai21/california-housing-dev:sha-b104c322c7ec3c29f8ebf16f60da9d3de2e52a43

          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10